import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WeddingPopup from "@/components/WeddingPopUp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PS Decor | Luxury Wedding & Event Decor Experts in India",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/favicon.ico",

  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WeddingPopup />
        {children}
      </body>
    </html>
  );
}
